/** RU microcopy — канон docs/discovery/design/sales-inbox-copy.md */
export const copy = {
  product_title: "Мониторинг тендеров",
  tab_lots: "Лоты",
  tab_ai_reviewed: "Разобрано с помощью ИИ",
  tab_run: "Прогон",
  login_username: "Логин",
  login_password: "Пароль",
  login_submit: "Войти",
  login_error: "Неверные логин или пароль",
  login_logout: "Выйти",
  login_busy: "Вход…",
  filter_unread: "Непросмотренные",
  filter_ai_reviewed: "Разобрано с помощью ИИ",
  action_ai_review: "Разобрать с ИИ",
  action_ai_review_busy: "ИИ разбирает…",
  action_ai_wrong: "ИИ ошибся",
  ai_banner_failures: "Сбои ИИ: {n}. Тир правил не меняли.",
  ai_error_label: "Ошибка ИИ",
  section_ai_reason: "Почему подходит (ИИ)",
  drawer_ai_suggested: "ИИ предложил: {ai} (было {rules})",
  drawer_rules_was: "По правилам было: {tier}",
  chip_ai_tier_hint: "ИИ: {tier}",
  ai_review_toast: "Разобрано {n}, перенесено {m}",
  empty_no_ai_title: "Ещё никто не разобран с ИИ",
  empty_no_ai_body: "Нажмите «Разобрать с ИИ» — лоты с доски пройдут проверку и появятся здесь с переносами между колонками.",
  filter_menu: "Фильтры",
  filter_menu_reset: "Сбросить фильтры",
  filter_priority_hot: "Горячие",
  filter_priority_strong: "Сильные",
  filter_priority_watch: "Смотреть",
  filter_deadline: "Срок подачи",
  filter_ingested: "Попало к нам",
  filter_date_any: "Любой",
  filter_date_any_f: "Любое",
  filter_deadline_7: "≤ 7 дней",
  filter_deadline_14: "≤ 14 дней",
  filter_deadline_30: "≤ 30 дней",
  filter_ingested_today: "Сегодня",
  filter_ingested_3: "За 3 дня",
  filter_ingested_7: "За 7 дней",
  filter_date_custom: "Свой период",
  filter_date_from: "С",
  filter_date_to: "По",
  search_placeholder: "Название, заказчик или номер",
  view_cards: "Доска",
  view_table: "Таблица",
  chip_hot: "Горячие",
  chip_strong: "Сильные",
  chip_watch: "Смотреть",
  chip_expired: "Просроченные",
  badge_deadline_expired: "Срок подачи вышел",
  action_archive: "В архив",
  action_restore_board: "Вернуть на доску",
  chip_overridden_suffix: "вручную",
  col_priority: "Приоритет",
  col_title: "Название",
  col_customer: "Заказчик",
  col_deadline: "Срок",
  col_price: "НМЦ",
  col_location: "Где работать",
  col_platform: "Площадка",
  platform_icon_aria: "Площадка: {name}",
  drawer_close_aria: "Закрыть",
  link_on_site: "На площадке",
  field_price: "НМЦ",
  field_deadline: "Срок подачи",
  field_region: "Регион",
  card_location: "Где работать",
  field_status: "Статус",
  field_empty: "Нет данных",
  section_fit: "Почему подходит",
  section_contacts: "Контакты",
  section_docs: "Документы",
  action_mark_viewed: "Отметить просмотренным",
  action_viewed_done: "Просмотрено",
  action_change_priority: "Изменить приоритет",
  action_reset_priority: "Сбросить",
  docs_empty_none: "К этой закупке нет приложенных файлов.",
  docs_download: "Скачать",
  empty_no_match_title: "Нет лотов по текущим фильтрам",
  empty_no_match_body: "Снимите часть фильтров или измените поисковый запрос.",
  empty_no_unread_title: "Все лоты просмотрены",
  empty_no_unread_body: "Снимите фильтр «Непросмотренные», чтобы увидеть все.",
  empty_no_data_title: "Пока нет подходящих лотов",
  empty_no_data_body: "Запустите прогон на вкладке «Прогон» или дождитесь окончания текущего.",
  empty_board_column: "Нет лотов",
  error_load_title: "Не удалось загрузить лоты",
  error_load_body:
    "Обновите страницу. Если ошибка повторяется — проверьте прогон на вкладке «Прогон».",
  override_menu_title: "Приоритет",
  override_done: "Приоритет изменён",
  run_section_controls: "Управление",
  run_section_groups: "Группы поиска",
  run_section_platforms: "Площадки",
  run_section_diagnostics: "Диагностика",
  run_idle_hint: "Нажмите «Старт», когда площадки и группы готовы.",
  run_running_hint: "Прогон идёт. «Стоп» прервёт текущий шаг и очередь.",
  run_queue_summary: "Очередь: {groups} групп × {platforms} площадки → {steps} шагов",
  run_queue_empty: "Очередь пуста — включите группу и площадку",
  run_queue_step: "Шаг {current}/{total} · {group} × {platform}",
  phase_idle: "Ожидание прогона",
  phase_list: "Фаза: список",
  phase_score: "Фаза: оценка",
  phase_cards: "Фаза: карточки",
  phase_artifacts: "Фаза: файлы",
  phase_done: "Прогон завершён",
  phase_partial: "Прогон завершён частично",
  phase_stopped: "Прогон остановлен",
  phase_error: "Прогон завершился с ошибкой",
  progress_list: "Список: {n} / {total}",
  progress_cards: "Карточки: {k} / {total}",
  counters_legend: "Счётчики L1–L3",
  run_report_legend: "Отчёт прогона",
  http_retries_label: "Повторы HTTP",
  run_report_new: "Новые лоты",
  run_report_already: "Уже были в системе",
  run_report_updated: "Обновлено с площадки",
  run_report_expired: "Ушли в просроченные",
  run_path_label: "Папка прогона",
  run_path_copy: "Копировать",
  run_path_copied: "Скопировано",
  log_title: "Лог",
  log_empty: "Записей пока нет",
  diagnostics_title: "Диагностика",
  diagnostics_expand: "Показать",
  diagnostics_collapse: "Скрыть",
  run_start: "Старт",
  run_stop: "Стоп",
  run_start_busy: "Запуск…",
  run_error_already: "Прогон уже идёт",
  run_error_cookies: "Нет сессии площадки — обновите сессию по инструкции",
  run_error_failed: "Не удалось запустить прогон. Обновите страницу и повторите.",
  run_error_empty_queue: "Включите хотя бы одну группу и одну площадку",
  platform_participate: "Участвует",
  platform_rostender: "РосТендер",
  platform_tender_pro: "Tender.Pro",
  platform_roseltorg: "Росэлторг",
  session_status_ok: "сессия в порядке",
  session_status_missing: "нет сессии",
  session_status_expired: "сессия устарела",
  session_status_list_without_login: "вход для списка не нужен",
  session_status_unknown: "статус неизвестен",
  session_hint_docs: "Как обновить сессию — в инструкции",
  platforms_none_enabled: "Нет включённых площадок",
  platforms_none_enabled_body: "Включите хотя бы одну площадку в блоке «Площадки».",
  groups_queue: "В очереди",
  groups_add: "Новая группа",
  groups_save: "Сохранить",
  groups_cancel: "Отмена",
  groups_delete: "Удалить",
  groups_edit: "Править",
  groups_name: "Имя",
  groups_queries: "Плюс — запросы (по одному на строку)",
  groups_exclude: "Минус — отсечь по заголовку",
  groups_exclude_hint:
    "Минус отсекает строки списка этой группы до доски. На другие группы не действует.",
  groups_limit: "Лимит",
  groups_limit_hint: "0 — без потолка",
  groups_empty: "Нет групп поиска",
  groups_empty_body:
    "Создайте группу с плюс-запросами — она пойдёт на все включённые площадки.",
  groups_none_queued: "Нет групп в очереди",
  groups_none_queued_body: "Включите «В очереди» хотя бы у одной группы.",
  groups_save_failed: "Не удалось сохранить группу",
  groups_duplicate_name: "Группа с таким именем уже есть",
  groups_delete_confirm: "Удалить эту группу?",
  groups_drawer_title: "Группа поиска",
  groups_drawer_close_aria: "Закрыть",
  queue_position: "Очередь: {current} из {total}",
  queue_status_pending: "ждёт",
  queue_status_running: "идёт",
  queue_status_done: "готово",
  queue_status_skipped: "пропущен",
  queue_status_error: "ошибка",
  queue_status_cancelled: "отменён",
} as const;
