/** RU microcopy — канон docs/discovery/design/sales-inbox-copy.md */
export const copy = {
  product_title: "Мониторинг тендеров",
  tab_lots: "Лоты",
  tab_run: "Прогон",
  login_username: "Логин",
  login_password: "Пароль",
  login_submit: "Войти",
  login_error: "Неверные логин или пароль",
  login_logout: "Выйти",
  login_busy: "Вход…",
  filter_unread: "Непросмотренные",
  filter_menu: "Фильтры",
  filter_menu_reset: "Сбросить фильтры",
  filter_priority_hot: "Горячие",
  filter_priority_strong: "Сильные",
  filter_priority_watch: "Смотреть",
  filter_deadline: "Срок подачи",
  filter_ingested: "Попало к нам",
  filter_date_any: "Любой",
  filter_date_any_f: "Любое",
  filter_deadline_7: "≤ 7 дней",
  filter_deadline_14: "≤ 14 дней",
  filter_deadline_30: "≤ 30 дней",
  filter_ingested_today: "Сегодня",
  filter_ingested_3: "За 3 дня",
  filter_ingested_7: "За 7 дней",
  filter_date_custom: "Свой период",
  filter_date_from: "С",
  filter_date_to: "По",
  search_placeholder: "Название, заказчик или номер",
  view_cards: "Доска",
  view_table: "Таблица",
  chip_hot: "Горячие",
  chip_strong: "Сильные",
  chip_watch: "Смотреть",
  chip_overridden_suffix: "вручную",
  col_priority: "Приоритет",
  col_title: "Название",
  col_customer: "Заказчик",
  col_deadline: "Срок",
  col_price: "НМЦ",
  col_location: "Где работать",
  col_platform: "Площадка",
  platform_icon_aria: "Площадка: {name}",
  drawer_close_aria: "Закрыть",
  link_on_site: "На площадке",
  field_price: "НМЦ",
  field_deadline: "Срок подачи",
  field_region: "Регион",
  card_location: "Где работать",
  field_status: "Статус",
  field_empty: "Нет данных",
  section_fit: "Почему подходит",
  section_contacts: "Контакты",
  section_docs: "Документы",
  action_mark_viewed: "Отметить просмотренным",
  action_viewed_done: "Просмотрено",
  action_change_priority: "Изменить приоритет",
  action_reset_priority: "Сбросить",
  docs_empty_none: "К этой закупке нет приложенных файлов.",
  docs_download: "Скачать",
  empty_no_match_title: "Нет лотов по текущим фильтрам",
  empty_no_match_body: "Снимите часть фильтров или измените поисковый запрос.",
  empty_no_unread_title: "Все лоты просмотрены",
  empty_no_unread_body: "Снимите фильтр «Непросмотренные», чтобы увидеть все.",
  empty_no_data_title: "Пока нет подходящих лотов",
  empty_no_data_body: "Запустите прогон на вкладке «Прогон» или дождитесь окончания текущего.",
  error_load_title: "Не удалось загрузить лоты",
  error_load_body:
    "Обновите страницу. Если ошибка повторяется — проверьте прогон на вкладке «Прогон».",
  override_menu_title: "Приоритет",
  override_done: "Приоритет изменён",
  session_ok: "Сессия: cookies OK",
  session_expired: "Сессия: cookies истекли — обновите файл cookies",
  session_missing: "Нет файла cookies — положите cookies по инструкции",
  phase_idle: "Ожидание прогона",
  phase_list: "Фаза: список",
  phase_score: "Фаза: оценка",
  phase_cards: "Фаза: карточки",
  phase_artifacts: "Фаза: файлы",
  phase_done: "Прогон завершён",
  phase_stopped: "Прогон остановлен",
  phase_error: "Прогон завершился с ошибкой",
  counters_legend: "Счётчики fit (L1–L3)",
  run_path_label: "Путь прогона",
  run_path_copy: "Копировать",
  run_path_copied: "Скопировано",
  log_title: "Лог",
  log_empty: "Записей пока нет",
  tech_readonly_note: "Старт и стоп прогона в этом экране отключены",
} as const;
