/** RU microcopy — канон docs/discovery/design/sales-inbox-copy.md */
export const copy = {
  product_title: "Разведчик",
  product_subtitle: "Мониторинг тендеров",
  tab_settings: "Настройки",
  tab_lots: "Лоты",
  tab_ai_reviewed: "Разобрано с помощью ИИ",
  tab_run: "Прогон",
  login_username: "Логин",
  login_password: "Пароль",
  login_submit: "Войти",
  login_error: "Неверные логин или пароль",
  login_logout: "Выйти",
  login_busy: "Вход…",
  filter_unread: "Непросмотренные",
  action_mark_all_viewed: "Отметить все просмотренными",
  mark_all_viewed_confirm_title: "Отметить просмотренными?",
  mark_all_viewed_confirm_body: "На этой вкладке непросмотренных: {n}. Продолжить?",
  mark_all_viewed_none: "Непросмотренных на этой вкладке нет",
  mark_all_viewed_done: "Отмечено просмотренными: {n}",
  mark_all_viewed_failed: "Не удалось отметить все просмотренными. Попробуйте ещё раз.",
  mark_all_viewed_confirm: "Отметить",
  mark_all_viewed_cancel: "Отмена",
  filter_ai_reviewed: "Разобрано с помощью ИИ",
  filter_ai_state_title: "Состояние ИИ",
  filter_ai_state_any: "Любой",
  filter_ai_state_none: "Без ИИ",
  filter_ai_state_done: "Разобран",
  filter_ai_state_failed: "Сбой ИИ",
  filter_ai_trigger_title: "Источник ИИ",
  filter_ai_trigger_any: "Любой",
  filter_ai_trigger_auto: "Авто",
  filter_ai_trigger_manual: "Вручную",
  filter_chip_ai_state: "ИИ: {value}",
  filter_chip_ai_trigger: "Источник ИИ: {value}",
  action_ai_review: "Разобрать с ИИ",
  action_ai_review_busy: "ИИ разбирает…",
  action_ai_retry_errors: "Доразобрать сбои",
  action_ai_wrong: "ИИ ошибся",
  ai_banner_failures: "Сбои ИИ: {n}. Тир правил не меняли.",
  ai_auto_incomplete:
    "ИИ не добил {n} лот(ов) — провайдер мог отвалиться. Нажмите «Доразобрать сбои» ниже (без нового прогона).",
  ai_error_label: "Ошибка ИИ",
  section_ai_reason: "Почему подходит (ИИ)",
  drawer_ai_suggested: "ИИ предложил: {ai} (было {rules})",
  drawer_rules_was: "По правилам было: {tier}",
  chip_ai_tier_hint: "ИИ: {tier}",
  ai_review_toast: "Разобрано {n}, перенесено {m}",
  ai_review_toast_failed: "Разобрано {n}, сбоев {m}. Можно доразобрать сбои.",
  ai_review_cap_hint: "До 100 заявок за раз",
  error_viewed_save: "Не удалось сохранить отметку «Просмотрено». Проверьте сеть и попробуйте ещё раз.",
  error_priority_save: "Не удалось сменить приоритет. Попробуйте ещё раз.",
  error_archive_save: "Не удалось скрыть карточку. Попробуйте ещё раз.",
  error_ai_action: "Не удалось выполнить действие с ИИ. Попробуйте ещё раз.",
  teach_dialog_title: "Оценка переноса",
  teach_drop_correct: "Лот уже в нужной колонке?",
  teach_yes: "Да",
  teach_no: "Нет",
  teach_reason_label: "Почему вы перенесли этот лот?",
  teach_reason_placeholder: "Кратко: почему эта колонка",
  teach_submit: "Сохранить",
  teach_cancel: "Отмена",
  teach_expired_hint:
    "Колонка «Просроченные» зависит от срока на площадке. Мы сохраним вашу оценку для обучения; карточка после сохранения останется там, куда указывает срок.",
  teach_saved: "Оценка сохранена",
  teach_save_failed: "Не удалось сохранить оценку. Попробуйте ещё раз.",
  settings_section_ai_prompt: "Системный промпт ИИ",
  ai_prompt_hint:
    "Этот текст уходит в модель при «Разобрать с ИИ». Ошибка в формулировке может сломать разбор. Сброс возвращает текст по умолчанию из поставки.",
  ai_prompt_default_badge: "Сейчас: текст по умолчанию",
  ai_prompt_custom_badge: "Сейчас: ваш текст",
  ai_prompt_save: "Сохранить промпт",
  ai_prompt_reset: "Сбросить к умолчанию",
  ai_prompt_saved: "Промпт сохранён",
  ai_prompt_reset_done: "Промпт сброшен к умолчанию",
  ai_prompt_invalid: "Промпт не может быть пустым",
  ai_prompt_save_failed: "Не удалось сохранить промпт",
  session_expired: "Сессия истекла. Войдите снова.",
  inbox_refreshing: "Обновляем список заявок…",
  empty_no_ai_title: "Ещё никто не разобран с ИИ",
  empty_no_ai_body: "Нажмите «Разобрать с ИИ» — лоты с доски пройдут проверку и появятся здесь с переносами между колонками.",
  filter_menu: "Фильтры",
  filter_menu_reset: "Сбросить фильтры",
  filter_section_dates: "Даты",
  filter_section_class: "Классификация",
  filter_section_source: "Источник",
  filter_priority_title: "Приоритет",
  filter_chips_clear_all: "Сбросить все",
  filter_chip_deadline: "Срок: {value}",
  filter_chip_ingested: "Попало: {value}",
  filter_chip_price: "НМЦ от {price}",
  filter_chip_platform: "Площадка ({n})",
  filter_chip_bitrix: "Битрикс: {value}",
  filter_chip_ai: "С ИИ",
  filter_chip_priority: "Приоритет: {value}",
  filter_priority_hot: "Горячие",
  filter_priority_strong: "Сильные",
  filter_priority_watch: "Смотреть",
  filter_deadline: "Срок подачи",
  filter_ingested: "Попало к нам",
  filter_date_any: "Любой",
  filter_date_any_f: "Любое",
  filter_deadline_7: "≤ 7 дней",
  filter_deadline_14: "≤ 14 дней",
  filter_deadline_30: "≤ 30 дней",
  filter_ingested_today: "Сегодня",
  filter_ingested_3: "За 3 дня",
  filter_ingested_7: "За 7 дней",
  filter_date_custom: "Свой период",
  filter_date_from: "С",
  filter_date_to: "По",
  filter_price: "НМЦ",
  filter_price_from: "От {price}",
  filter_price_show_all: "Показать все",
  filter_price_settings_link: "Изменить в Настройках",
  filter_platform: "Площадка",
  filter_bitrix: "Битрикс",
  filter_bitrix_any: "Любой",
  filter_bitrix_in: "В Битрикс",
  filter_bitrix_out: "Не в Битрикс",
  search_placeholder: "Название, заказчик или номер",
  view_cards: "Доска",
  view_table: "Таблица",
  sort_relevance: "Релевантность",
  sort_appeared: "Появление",
  sort_deadline: "Срок",
  sort_group_aria: "Сортировка списка",
  chip_hot: "Горячие",
  chip_strong: "Сильные",
  chip_watch: "Смотреть",
  chip_expired: "Просроченные",
  badge_deadline_expired: "Срок подачи вышел",
  action_archive: "В архив",
  action_restore_board: "Вернуть на доску",
  action_bitrix: "Отправить в Битрикс",
  action_bitrix_busy: "Отправляю…",
  bitrix_sent_ok: "Отправлено в Битрикс",
  bitrix_already: "Уже отправлено в Битрикс",
  bitrix_error: "Не удалось отправить в Битрикс",
  bitrix_unconfigured: "Битрикс не настроен (нет вебхука)",
  chip_overridden_suffix: "вручную",
  col_priority: "Приоритет",
  col_title: "Название",
  col_customer: "Заказчик",
  col_deadline: "Срок",
  col_published: "На площадке",
  col_ingested: "Попало к нам",
  col_price: "НМЦ",
  col_location: "Где работать",
  col_platform: "Площадка",
  platform_icon_aria: "Площадка: {name}",
  drawer_close_aria: "Закрыть",
  link_on_site: "На площадке",
  field_price: "НМЦ",
  field_deadline: "Срок подачи",
  field_published: "На площадке",
  field_ingested: "Попало к нам",
  field_region: "Регион",
  card_location: "Где работать",
  field_status: "Статус",
  field_empty: "Нет данных",
  section_fit: "Почему подходит",
  section_contacts: "Контакты",
  section_docs: "Документы",
  action_mark_viewed: "Отметить просмотренным",
  action_viewed_done: "Просмотрено",
  action_change_priority: "Изменить приоритет",
  action_reset_priority: "Сбросить",
  docs_empty_none: "К этой закупке нет приложенных файлов.",
  docs_empty_pending_ai: "Файлы появятся после разбора с ИИ.",
  docs_empty_pending_download: "Скачиваем документацию…",
  docs_empty_not_downloaded: "Файлы ещё не скачаны. Появятся после разбора с ИИ.",
  docs_external_only: "Документация на площадке закупки. Откройте ссылку и скачайте там.",
  docs_external_open: "Открыть на площадке",
  docs_unsupported_platform: "Файлы этой площадки пока не качаем.",
  docs_error: "Не удалось скачать документы.",
  docs_download: "Скачать",
  empty_no_match_title: "Нет лотов по текущим фильтрам",
  empty_no_match_body: "Снимите часть фильтров или измените поисковый запрос.",
  empty_no_unread_title: "Все лоты просмотрены",
  empty_no_unread_body: "Снимите фильтр «Непросмотренные», чтобы увидеть все.",
  empty_no_data_title: "Пока нет подходящих лотов",
  empty_no_data_body: "Нажмите «Запустить прогон» на вкладке «Лоты» или дождитесь автослота.",
  empty_board_column: "Нет лотов",
  error_load_title: "Не удалось загрузить лоты",
  error_load_body:
    "Обновите страницу. Если ошибка повторяется — откройте «Настройки» и проверьте сессии.",
  override_menu_title: "Приоритет",
  override_done: "Приоритет изменён",
  run_section_controls: "Управление",
  run_section_groups: "Группы поиска",
  run_section_platforms: "Площадки",
  run_section_diagnostics: "Диагностика",
  run_idle_hint: "Нажмите «Запустить прогон», когда площадки и группы готовы.",
  run_running_hint: "Прогон идёт. «Стоп» прервёт текущий шаг и очередь.",
  run_queue_summary: "{groups} групп × {platforms} площадок · {steps} шагов",
  run_queue_empty: "Очередь пуста — включите группу и площадку",
  run_queue_step: "Шаг {current}/{total} · {group} × {platform}",
  run_chip_idle: "Ожидание",
  run_chip_running: "Прогон",
  run_chip_done: "Готово",
  run_chip_partial: "Частично",
  run_chip_stopped: "Остановлен",
  run_chip_error: "Ошибка",
  progress_list_label: "Список",
  progress_cards_label: "Карточки",
  tier_label_l1: "L1",
  tier_label_l2: "L2",
  tier_label_l3: "L3",
  tier_label_noise: "noise",
  phase_idle: "Ожидание прогона",
  phase_list: "Фаза: список",
  phase_score: "Фаза: оценка",
  phase_cards: "Фаза: карточки",
  phase_artifacts: "Фаза: файлы",
  phase_done: "Прогон завершён",
  phase_partial: "Прогон завершён частично",
  phase_stopped: "Прогон остановлен",
  phase_error: "Прогон завершился с ошибкой",
  progress_list: "Список: {n} / {total}",
  progress_cards: "Карточки: {k} / {total}",
  counters_legend: "Счётчики L1–L3",
  run_report_legend: "Отчёт прогона",
  http_retries_label: "Повторы HTTP",
  run_report_new: "Новые лоты",
  run_report_already: "Уже были в системе",
  run_report_updated: "Обновлено с площадки",
  run_report_expired: "Ушли в просроченные",
  run_path_label: "Папка прогона",
  run_path_copy: "Копировать",
  run_path_copied: "Скопировано",
  log_title: "Лог",
  log_empty: "Записей пока нет",
  diagnostics_title: "Диагностика",
  diagnostics_expand: "Показать",
  diagnostics_collapse: "Скрыть",
  run_start: "Запустить прогон",
  run_stop: "Стоп",
  run_start_busy: "Запуск…",
  run_error_already: "Прогон уже идёт",
  run_error_cookies: "Нет сессии площадки — обновите сессию по инструкции",
  run_error_failed: "Не удалось запустить прогон. Обновите страницу и повторите.",
  run_error_empty_queue: "Включите хотя бы одну группу и одну площадку",
  platform_participate: "Участвует",
  platform_rostender: "РосТендер",
  platform_tender_pro: "Tender.Pro",
  platform_roseltorg: "Росэлторг",
  platform_b2b_center: "B2B-Center",
  platform_rts_rosatom: "РТС (Росатом)",
  platform_oilb2bcs: "OilB2B",
  platform_sibur_srm: "СИБУР SRM",
  session_status_ok: "сессия в порядке",
  session_status_missing: "нет сессии",
  session_status_expired: "сессия устарела",
  session_status_blocked: "captcha / блокировка IP",
  session_status_list_without_login: "вход для списка не нужен",
  session_status_unknown: "статус неизвестен",
  session_hint_docs: "Как обновить сессию — в инструкции",
  platforms_none_enabled: "Нет включённых площадок",
  platforms_none_enabled_body: "Включите хотя бы одну площадку в блоке «Площадки».",
  groups_queue: "В очереди",
  groups_add: "Новая группа",
  groups_save: "Сохранить",
  groups_cancel: "Отмена",
  groups_delete: "Удалить",
  groups_edit: "Править",
  groups_name: "Имя",
  groups_queries: "Плюс — запросы (по одному на строку)",
  groups_exclude: "Минус — отсечь по заголовку",
  groups_exclude_hint:
    "Минус отсекает строки списка этой группы до доски. На другие группы не действует.",
  groups_limit: "Лимит",
  groups_limit_hint: "0 — без потолка",
  groups_empty: "Нет групп поиска",
  groups_empty_body:
    "Создайте группу с плюс-запросами — она пойдёт на все включённые площадки.",
  groups_none_queued: "Нет групп в очереди",
  groups_none_queued_body: "Включите «В очереди» хотя бы у одной группы.",
  groups_save_failed: "Не удалось сохранить группу",
  groups_duplicate_name: "Группа с таким именем уже есть",
  groups_delete_confirm: "Удалить эту группу?",
  groups_drawer_title: "Группа поиска",
  groups_drawer_close_aria: "Закрыть",
  queue_position: "Очередь: {current} из {total}",
  queue_status_pending: "ждёт",
  queue_status_running: "идёт",
  queue_status_done: "готово",
  queue_status_skipped: "пропущен",
  queue_status_error: "ошибка",
  queue_status_cancelled: "отменён",
  auto_slot_idle: "Автослот: {when} МСК",
  auto_slot_running: "Идёт авторазбор…",
  auto_slot_skipped_already_running: "Слот пропущен: прогон уже шёл",
  auto_slot_skipped_empty_queue: "Слот пропущен: нет групп или площадок в очереди",
  auto_slot_last: "Последний запуск: {datetime}",
  auto_session_banner: "Сессия площадки устарела или отсутствует — обновите в Настройках",
  auto_session_banner_action: "Открыть Настройки",
  auto_lead_hint:
    "После ИИ лоты L1 уходят в Битрикс и чат «Тендеры». Остальные — вручную.",
  empty_auto_title: "Пока нет лотов авторазбора",
  empty_auto_body: "Дождитесь слота или проверьте сессии площадок в Настройках.",
  empty_auto_no_match_title: "Нет лотов по фильтру",
  empty_auto_no_match_body: "Сбросьте фильтры или измените условия поиска.",
  empty_auto_no_unread_title: "Нет непросмотренных",
  empty_auto_no_unread_body: "Все лоты авторазбора уже просмотрены.",
  error_auto_load_title: "Не удалось загрузить авторазбор",
  error_auto_load_body:
    "Обновите страницу. Если ошибка повторяется — откройте Настройки и проверьте сессии.",
  ai_eta_progress: "Разбираю {n} из {m}…",
  ai_eta_done: "Разбор с ИИ завершён",
  manual_lead_hint:
    "С ручного прогона автолиды L1 уходят после «Разобрать с ИИ». Кнопка в карточке — для остальных.",
  manual_session_muted: "Если сессия площадки устарела — обновите её в Настройках.",
  filter_ai_reviewed_trigger: "С ИИ",
  filter_ai_reviewed_menu_title: "Разбор ИИ",
  chip_ai_reviewed: "ИИ",
  empty_manual_title: "Нет лотов",
  empty_manual_body: "Нажмите «Запустить прогон», чтобы запустить прогон.",
  empty_manual_queue: "В очереди нет шагов — включите группы и площадки в Настройках.",
  error_manual_load_title: "Не удалось загрузить лоты",
  error_manual_load_body:
    "Обновите страницу. Если ошибка повторяется — проверьте ход прогона выше.",
  settings_section_schedule: "Расписание",
  settings_section_min_price: "Мин. НМЦ для Горячих",
  settings_section_platforms: "Площадки и сессии",
  settings_section_groups: "Группы поиска",
  settings_section_diagnostics: "Диагностика",
  schedule_enabled: "Включено",
  schedule_time: "Время (МСК)",
  schedule_weekdays: "Дни недели",
  schedule_day_mon: "Пн",
  schedule_day_tue: "Вт",
  schedule_day_wed: "Ср",
  schedule_day_thu: "Чт",
  schedule_day_fri: "Пт",
  schedule_day_sat: "Сб",
  schedule_day_sun: "Вс",
  schedule_weekdays_hint: "Прогон только в отмеченные дни (по Москве)",
  schedule_invalid_weekdays: "Выберите хотя бы один день",
  schedule_save: "Сохранить",
  schedule_saved: "Расписание сохранено",
  schedule_invalid_time: "Укажите время в формате ЧЧ:ММ",
  schedule_save_failed: "Не удалось сохранить расписание. Проверьте сеть и попробуйте ещё раз.",
  schedule_disabled_hint: "Авторазбор выключен — слот не запускается",
  min_price_hint:
    "Лоты дешевле порога не попадают в «Горячие» и не уходят в L1-почту. На доске по умолчанию скрыты.",
  min_price_value: "Порог: {price}",
  min_price_save: "Сохранить",
  min_price_saved: "Порог сохранён",
  min_price_invalid: "Укажите сумму от 0 до 5 000 000 ₽",
  min_price_save_failed: "Не удалось сохранить порог",
  cookies_upload: "Загрузить файл",
  cookies_paste: "Вставить JSON",
  cookies_paste_hide: "Скрыть вставку",
  cookies_paste_placeholder: "Вставьте JSON-массив cookie…",
  cookies_format_hint: "Формат: JSON из расширения Get cookies.txt LOCOR",
  cookies_submit: "Сохранить сессию",
  cookies_busy: "Сохраняем…",
  cookies_ok: "Сессия обновлена",
  cookies_on_server: "Сессия на сервере",
  cookies_expired: "Сессия устарела — загрузите новый JSON",
  cookies_missing: "Нет сессии — загрузите JSON",
  cookies_invalid: "Неверный JSON — проверьте файл и вставьте снова",
  export_button: "Экспорт",
  export_drawer_title: "Экспорт лотов",
  export_section_format: "Формат",
  export_section_columns: "Колонки",
  export_section_lots: "Какие лоты",
  export_format_csv: "CSV",
  export_format_xlsx: "Excel (XLSX)",
  export_preset_ai: "Разбор ИИ",
  export_columns_all: "Все колонки",
  export_columns_helper: "По умолчанию — поля для разбора ошибок ИИ.",
  export_count: "К выгрузке: {n}",
  export_download: "Скачать",
  export_download_busy: "Готовим файл…",
  export_empty_title: "Нет лотов по условиям",
  export_empty_body: "Измените фильтры в этом окне или на доске.",
  export_error: "Не удалось выгрузить — попробуйте ещё раз.",
  export_filter_ai_wrong: "ИИ ошибся",
  export_drawer_close_aria: "Закрыть",
} as const;
