export const labCopy = {
  page_title: "Lab — run chrome",
  page_hint: "Только DEV. Кнопки меняют mock-состояние, API не вызывается.",
  preset_label: "Состояние mock",
  variant_label: "Сценарий",
  back_to_app: "Открыть продукт (/)",

  preset_idle: "Ожидание",
  preset_running: "Прогон идёт",
  preset_done: "Прогон готов",
  preset_ai_busy: "ИИ разбирает",
  preset_ai_done: "ИИ готов",

  a_title: "A — Компактный двухшаговый",
  a_blurb: "Тот же продукт: прогон → отдельно ИИ. Читаемая иерархия и глаголы.",
  a_slot: "Автослот: {when} МСК",
  a_run_start: "Запустить прогон",
  a_run_stop: "Стоп",
  a_status_idle: "Ожидание",
  a_status_running: "Прогон",
  a_status_done: "Готово",
  a_queue: "{groups} групп × {platforms} площадок · {steps} шагов",
  a_progress_list: "Список",
  a_progress_cards: "Карточки",
  a_tier_l1: "L1",
  a_tier_l2: "L2",
  a_tier_l3: "L3",
  a_tier_noise: "noise",
  a_ai: "Разобрать с ИИ",
  a_ai_busy: "Разбираю…",
  a_ai_hint: "До 100 заявок за раз",
  a_bitrix: "После ИИ лоты L1 уходят в Битрикс и чат «Тендеры». Остальные — вручную.",

  b_title: "B — Единый поток смены",
  b_blurb: "Одна смена: primary «Прогнать и разобрать»; отдельно — только прогон или только ИИ.",
  b_slot: "Следующий автослот {when} МСК",
  b_status_idle: "Готово к запуску · {steps} шагов",
  b_status_running: "Идёт прогон · список {n}/{total}",
  b_status_done: "Прогон завершён · к разбору ИИ: {pending}",
  b_status_ai: "Разбор ИИ · {pending} в работе",
  b_status_ai_done: "Смена закрыта по ИИ",
  b_primary: "Прогнать и разобрать",
  b_primary_busy: "Смена в работе…",
  b_primary_hint: "Список → карточки → ИИ до 100 заявок",
  b_only_run: "Только прогон",
  b_only_ai: "Только ИИ",
  b_stop: "Остановить",
  b_outcome: "L1 уйдут в Битрикс и чат «Тендеры»",
  b_counters: "L1 {l1} · L2 {l2} · L3 {l3}",

  c_title: "C — Сегодняшняя очередь",
  c_blurb: "Сначала «что сделать сейчас»; кнопка — следствие первого открытого пункта.",
  c_now: "Сейчас",
  c_item_run: "Прогон: {groups} групп × {platforms} площадок",
  c_item_run_done: "Прогон выполнен",
  c_item_ai: "Без разбора ИИ: {n}",
  c_item_ai_done: "Разбор ИИ выполнен",
  c_item_manual: "К отправке вручную: {n}",
  c_item_manual_hint: "L1 уже в Битрикс и чат — здесь остальные",
  c_cta_run: "Запустить прогон",
  c_cta_ai: "Разобрать с ИИ",
  c_cta_manual: "К доске",
  c_stop: "Стоп",
  c_slot: "Автослот {when} МСК",
  c_summary: "L1 {l1} · L2 {l2} · L3 {l3} · noise {noise}",
} as const;

export type LabCopy = typeof labCopy;
